name: CI/CD Pipeline Test
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/test/Test-CI-CD/
            git pull origin master
            npm install
            pm2 restart all || pm2 start npm --name "cicd" -- start